### ISSUE TITLE
19 scripts in script2font.csv present in langtags, but not "y" in "In langtags" column

### ISSUE THREAD

**Issue by imnasnainaec** [silnrsi/langfontfinder#6]
Aghb, Bhks, Cirt, Dogr, Dupl, Gong, Gonm, Hmnp, Mahj, Maka, Maya, Medf, Mult, Nkdb, Piqd, Sara, Sidd, Teng, Wcho

All are present as scripts in `testdata/langtags.json`, https://github.com/silnrsi/langtags/blob/master/source/langtags.csv, and https://ldml.api.sil.org/en?query=langtags

**Comment by DavidLRowe** [comment]
Fixed in commit https://github.com/silnrsi/langfontfinder/commit/9439c9ad67bdd86ea3363fc288b40ff301e09be3

Thanks @imnasnainaec for pointing this out.
